name: PR to main branch zip generate

on:
  pull_request:
    branches: [ "main" ]
    paths: 
    - 'ants/**'
    - 'base/**'
    - 'browserspecific/**'

jobs:
  pr-generate-zips:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
        distribution: 'temurin'
    - name: Build with Ant
      run: ant -noinput -buildfile ants/build.xml
    - name: Setting date and time in env variable
      run: echo "date-time-env=$(date '+%Y%m%d-%H%M%S')" >> $GITHUB_ENV
    - uses: actions/upload-artifact@v3
      name: Uploading generated zip files
      with:
        name: pr-zips-${{ env.date-time-env }}
        path: generated/zip-deploy/*.zip
